### ISSUE TITLE
1 day 3 questions 는 너무 뜨겁습니다.

### ISSUE THREAD

**Issue by JustKode** [FacerAin/Algorithm-Study#1]
역시 **강한 남자** 쏭용우... <br><br>
<img src="https://scontent-gmp1-1.xx.fbcdn.net/v/t1.0-9/21077569_800915856748753_2835217324346577206_n.jpg?_nc_cat=104&_nc_oc=AQmoLgeNS7bLwM2LuRNtl21E9pAlkHrBNhD1xv3PXgevmNN_slsHZYVwoObgpyIBaGA&_nc_ht=scontent-gmp1-1.xx&oh=5bc2b432f5d868b375b16b6afc1df743&oe=5DF9C3EC"></img>

**Comment by FacerAin** [comment]
너무 뜨거운 나머지 불타 없어져버렸습니다...
